name: 'Build Commit'
on:
  push:
    branches:
      - 'main'
      - 'master'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.[0-9]+'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-[0-9]+.[0-9]+'

jobs:
  build:
    uses: MinecraftschurliMods/.github/.github/workflows/build-library.yml@main
    with:
      maven-url: ${{ vars.MAVEN_URL }}
      maven-user: ${{ vars.MAVEN_USER }}
      publish-to-maven: true
    secrets:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
